server 

	listen 	8888
	server_name     test42

	error_page	400 error/400.html
	error_page	403 error/403.html
	error_page	404 error/404.html
	error_page	405 error/405.html
	error_page	411 error/411.html
	error_page	413 error/413.html
	error_page	501 error/501.html
	error_page	505 error/505.html

	location / 
        allow 	GET
		root	/webdata
        index	/webdata/index.html
        ext		bla
		cgi		/CGIScript
	

    location /directory 
		allow 	GET
        allow 	POST
		root	/YoupiBanane
		index	/webdata/index.html
		ext		bla
		cgi		/CGIScript
	

    location /put_test 
        allow 	PUT
        root	/webdata
		upload	/webdata
    
    
    location /post_body 
		allow 		POST
		root		/webdata
		index		/webdata/index.html
		max_body	bla
		ext			/CGIScript
		client_max_body_size	100


	
