# Webserv Configuration File ™

server
	# 1/ Choose the port and host of each server
	# 2/ Setup the server_name(s) or not (localhost by default)
	listen		42
	server_name	school

	# 3/ Setup default error pages
	error_page	403 /forbidden.html
	error_page	404 /not_found.html

	# 4/ Limit client body size (1MB by default)
	client_max_body_size 42M

	# 5/ Setup routes with one or multiple of the following rules/configuration
	location	/methods
		# 5a/ Define a list of accepted HTTP methods for the route (false by default)
		allow 	GET
		allow 	POST
		allow 	DELETE

	location	/42
		# 5b/ Define a HTTP redirection (check expected 30X status codes)
		redirect https://www.42network.org/

	location	/pictures
		# 5c/ Define a directory or a file from where the file should be searched
		root	/www/media/

	location	/cloud
		# 5d/ Turn on or off directory listing (off by default)
		autoindex on

	location	/index
		# 5e/ Set a default file to answer if the request is a directory
		index	/index.html

	# [TODO] 5f/ Execute CGI based on certain file extension (for example .php) and make it work with POST and GET methods.

	location	/sendfeetpics
		# 5g/ Make the route able to accept uploaded files and configure where they should be saved.
		allow	POST
		upload	/www/data/

server
	listen		19
	server_name	campus

server
	listen		80
