server {
	listen					42;				# Port
	server_name				school;			# Hostname
	error_page				404	/404.html;	# Default error page
	error_page				500 502 503 504 404 /error.html;
	client_max_body_size 	42M;			# Client body size limit
	location				/media {		# Specify route for rules
		limit_except GET POST DELETE {		# Define accepted methods
			deny all;
		}
	}
	location				/42 {			# Permanent redirection rule
		return	301	https://www.42network.org/$request_uri
	}
	location				/wip {			# Temporary redirection rule
		return	302	https://www.42network.org/$request_uri
	}
}

server {
	listen			19;
	server_name		campus;
}

server {
	listen			80;
}
